apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ userID }}
  namespace: {{ userID }}
  labels:
    app: {{ userID }}
spec:
  selector:
    matchLabels:
      app: {{ userID }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ userID }}
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R www-data:www-data /var/www/html"]
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      containers:
      - image: wordpress
        name: {{ userID }}
        env:
        - name: WORDPRESS_DB_HOST
          value: docker.lala-1992.xyz
        - name: WORDPRESS_DB_USER
          value: {{ userID }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ userID }}
        - name: WORDPRESS_DB_NAME
          value: {{ userID }} 
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        - name: apache-config
          mountPath: /etc/apache2/conf.d
      volumes:
      - name: wordpress-persistent-storage
        emptyDir: {}  # Adjust this based on your storage requirements
      - name: apache-config
        configMap:
          name: apache-config